<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <p><a id="logo" href="http://scala-lang.org/"><img src="/sites/default/files/icons/Scala_Logo2008.png" alt="scala-lang.org" border=0/></a></p>
    <title id="Title">Aladdin - Scala Bugtracking</title>
        <style type="text/css">
        table {
            font-size: 10pt;
            background-color: #ebb85c;
        }
        tr.impair        { background-color: #f0be64 }
        tr.impairContrib { background-color: #f0be64 }

#buraq-content {
	float: none;
	color: black;
	background-color: white;
	font-size: 1.25em;
	margin-left: 9.6em;
}
        </style>
      </head>
  <body><!--DisplayBugsBlock_Start-->




<table WIDTH="100%" cellspacing="4" cellpadding="2">

	<tr><td></td>
		<th>[#1168]</th>
		<th><strong>project:</strong> compiler</th>
		<th><strong>priority:</strong> low</th>
		<th><strong>category:</strong> bug</th>
        </tr>

        <tr>
          <td></td>
	  <th align="center">submitter</th>
	  <th align="center">assigned to</th>
	  <th align="center">status</th>
	  <th align="center">date submitted</th>
        </tr>

        <tr>
          <td></td>
	  <td align="center" bgcolor="#FFFFFF">Iulian</td>
	  <td align="center" bgcolor="#FFFFFF">Martin</td>
	  <td align="center" bgcolor="#FFFFFF">fixed</td>
          <td align="center" bgcolor="#FFFFFF">2007-06-05 10:16:42.0</td>

	</tr>

        <tr>
		<th align="right">subject</th>
		<td colspan="4" bgcolor="#FFFFFF">[contrib #649] matching code for thrown exceptions broken</td>
	</tr>
	<tr>	
		<th align="right">code</th>
		<td colspan="4" bgcolor="#FFFFFF">
	<font size="-1"><pre>object ExceptionHandlingTest extends Application {
  
  trait SpecialException {}

  try {
    throw new Exception
  } catch {
    case e : SpecialException =&gt; {
      println(&quot;matched SpecialException&quot;)
      assume(e.isInstanceOf[SpecialException])
    }
    case e : Exception =&gt; {
      assume(e.isInstanceOf[Exception])
    }
  }
}</pre></font></td>
	</tr>
	<tr>
		<th style="text-align:right;">what happened</th>
		<td colspan="4" style="background-color:#FFFFFF;" ><pre>matching on a thrown exception behaves differently than regular matching.
</pre></td>
	</tr>
	<tr>
		<th align="right">what expected</th>
		<td colspan="4" bgcolor="#FFFFFF" >no assumptions should fail.  matching success</td>
	</tr>
	<tr>
	
  <td colspan="4" align="right">
      
      <a href="displayBugs.do.html">
        [back to overview]</a></td></tr>

</table>

  <tr>
          <td align="center" colspan="2">
            <strong>Changes of this bug report</strong>
          </td>
        </tr><table><tr>
        <td>
        <strong>Iulian&nbsp; edited on &nbsp;2007-06-05 10:17:13.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>

</td></tr>
<tr>
        <td>
        <strong>Iulian&nbsp; edited on &nbsp;2007-06-05 11:35:21.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>
I simplified the example. I have the feeling it's the new unapply patterns at the root of this bug, but I'm not sure. Here's what I know:

 - the first typed pattern (e: SpecialException) does not conform to the prototype (java.lang.Throwable). Instead of failing, the type checker changes it to (e: Throwable with SpecialException).
 - Erasure makes 'e' just a Throwable, and adds the appropriate casts in the body. Since this happens after patternmatching, the additional check for SpecialException is missing.
 - the backend adds an exception handler for Throwable, which catches everything.

The spec says that the patterns in a try-catch must conform to Throwable, and does not say anything about the silent addition of Throwable. But I guess the original poster's intuition, that pattern matching and exception matching should agree, is the right one.
</td></tr>
<tr>
        <td>
        <strong>Martin&nbsp; edited on &nbsp;2007-07-02 18:24:39.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>
The example now compiles and runs OK.

</td></tr></table>
<!--DisplayBugsBlock_End-->  </body>
</html>