<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <p><a id="logo" href="http://scala-lang.org/"><img src="/sites/default/files/icons/Scala_Logo2008.png" alt="scala-lang.org" border=0/></a></p>
    <title id="Title">Aladdin - Scala Bugtracking</title>
        <style type="text/css">
        table {
            font-size: 10pt;
            background-color: #ebb85c;
        }
        tr.impair        { background-color: #f0be64 }
        tr.impairContrib { background-color: #f0be64 }

#buraq-content {
	float: none;
	color: black;
	background-color: white;
	font-size: 1.25em;
	margin-left: 9.6em;
}
        </style>
      </head>
  <body><!--DisplayBugsBlock_Start-->




<table WIDTH="100%" cellspacing="4" cellpadding="2">

	<tr><td></td>
		<th>[#629]</th>
		<th><strong>project:</strong> compiler</th>
		<th><strong>priority:</strong> low</th>
		<th><strong>category:</strong> bug</th>
        </tr>

        <tr>
          <td></td>
	  <th align="center">submitter</th>
	  <th align="center">assigned to</th>
	  <th align="center">status</th>
	  <th align="center">date submitted</th>
        </tr>

        <tr>
          <td></td>
	  <td align="center" bgcolor="#FFFFFF">Nikolay</td>
	  <td align="center" bgcolor="#FFFFFF">Martin</td>
	  <td align="center" bgcolor="#FFFFFF">fixed</td>
          <td align="center" bgcolor="#FFFFFF">2006-06-19 15:26:43.0</td>

	</tr>

        <tr>
		<th align="right">subject</th>
		<td colspan="4" bgcolor="#FFFFFF">[contrib #157] VerifyError: Illegal use of nonvirtual function call</td>
	</tr>
	<tr>	
		<th align="right">code</th>
		<td colspan="4" bgcolor="#FFFFFF">
	<font size="-1"><pre>object Test
{
    def main(args : Array[String]) : Unit = Console.println(new C(1))
}

abstract class A(val x : Int)

class C(x : Int) extends A(x)
{
    val v = new D
    class D { def value = x }
}</pre></font></td>
	</tr>
	<tr>
		<th style="text-align:right;">what happened</th>
		<td colspan="4" style="background-color:#FFFFFF;" ><pre>At runtime:

<pre>
Exception in thread "main" java.lang.VerifyError: (class: C$D, method: value signature: ()I) Illegal use of nonv\
irtual function call
        at C.<init>(test.scala:10)
        at Test$.main(test.scala:3)
        at Test.main(test.scala)
</pre>
</pre></td>
	</tr>
	<tr>
		<th align="right">what expected</th>
		<td colspan="4" bgcolor="#FFFFFF" >Prints something like:

C@b8df17</td>
	</tr>
	<tr>
	
  <td colspan="4" align="right">
      
      <a href="displayBugs.do.html">
        [back to overview]</a></td></tr>

</table>

  <tr>
          <td align="center" colspan="2">
            <strong>Changes of this bug report</strong>
          </td>
        </tr><table><tr>
        <td>
        <strong>Nikolay&nbsp; edited on &nbsp;2006-06-19 15:27:15.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>

</td></tr>
<tr>
        <td>
        <strong>Iulian&nbsp; edited on &nbsp;2006-06-19 17:41:46.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>
It seems that an 'outer' reference is missing. Here's the output after mixin:

class C$D {
...
    def value(): scala.Int = C.super[A].x();
..
}

but C is the outer class of D (which indeed has A as ancestor). I think the code for 'value' should be:

    def value(): scala.Int = $outer.x();

In fact, this bug can be triggered by simply calling a method through 'super' on an outer class. To fix, it's needed both a super accessor in class A, and a proper 'outer' path in the inner class D.
</td></tr>
<tr>
        <td>
        <strong>Martin&nbsp; edited on &nbsp;2006-06-21 17:15:12.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>
The problem was a wrong phase ordering. Fixed by moving some code from refchecks to superaccessors.

</td></tr>
<tr>
        <td>
        <strong>Martin&nbsp; edited on &nbsp;2006-06-21 17:15:44.0</strong>
        </td>
        </tr>
<tr><td bgcolor='#FFFFFF'>

</td></tr></table>
<!--DisplayBugsBlock_End-->  </body>
</html>